export const apiIndexResponse = {
  message: 'NTU Mods by Bob Backend API',
  version: '1.0.0',
  status: 'active',
  documentation: '/api-docs',
  endpoints: {
    auth: {
      register: 'POST /api/auth/register',
      login: 'POST /api/auth/login',
      refresh: 'POST /api/auth/refresh',
      config: 'GET /api/auth/config',
      googleCallback: 'GET /api/auth/google/callback',
      githubCallback: 'GET /api/auth/github/callback',
      profile: 'GET /api/auth/me',
      updateProfile: 'PUT /api/auth/me',
      avatar: 'POST /api/auth/avatar',
      changePassword: 'POST /api/auth/change-password',
      deleteAccount: 'DELETE /api/auth/account',
      emailChangeRequest: 'POST /api/auth/email-change/request',
      emailChangeVerify: 'POST /api/auth/email-change/verify',
      emailChangeRevert: 'POST /api/auth/email-change/revert',
      linkGoogle: 'POST /api/auth/oauth/link/google',
      linkGithub: 'POST /api/auth/oauth/link/github',
      unlinkProvider: 'DELETE /api/auth/oauth/link/:provider',
    },
    health: {
      basic: 'GET /api/health',
      detailed: 'GET /api/health/detailed',
      version: 'GET /api/health/version',
    },
    catalogue: {
      list: 'GET /api/modules',
      stats: 'GET /api/modules/stats',
      search: 'GET /api/modules/search',
      searchAll: 'GET /api/modules/search-all',
      details: 'GET /api/modules/:code',
      indexes: 'GET /api/modules/:code/indexes',
      prerequisites: 'GET /api/modules/:code/prerequisites',
      dependencies: 'GET /api/modules/:code/dependencies',
      semesters: 'GET /api/semesters',
    },
    timetables: {
      list: 'GET /api/timetables',
      create: 'POST /api/timetables',
      get: 'GET /api/timetables/:id',
      update: 'PUT /api/timetables/:id',
      delete: 'DELETE /api/timetables/:id',
      addModule: 'POST /api/timetables/:id/modules',
      removeModule: 'DELETE /api/timetables/:id/modules/:code',
      conflicts: 'GET /api/timetables/:id/conflicts',
      generate: 'POST /api/timetables/generate',
    },
    coursePlan: {
      get: 'GET /api/plan',
      save: 'POST /api/plan',
    },
    timetableGeneration: {
      generate: 'POST /api/timetable/generate',
      validate: 'POST /api/timetable/validate',
    },
    user: {
      avatar: 'GET /api/user/:userId/avatar',
      settings: 'GET /api/user/settings',
      updateSettings: 'PUT /api/user/settings',
    },
    moduleReviews: {
      list: 'GET /api/modules/:moduleCode/reviews',
      create: 'POST /api/modules/:moduleCode/reviews',
      update: 'PUT /api/modules/:moduleCode/reviews/:reviewId',
      delete: 'DELETE /api/modules/:moduleCode/reviews/:reviewId',
      vote: 'POST /api/modules/:moduleCode/reviews/:reviewId/vote',
    },
    moduleTopics: {
      list: 'GET /api/modules/:moduleCode/topics',
      create: 'POST /api/modules/:moduleCode/topics',
      update: 'PUT /api/modules/:moduleCode/topics/:topicId',
      delete: 'DELETE /api/modules/:moduleCode/topics/:topicId',
      vote: 'POST /api/modules/:moduleCode/topics/:topicId/vote',
    },
  },
};

